export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/auth'
export const BASKET_ROUTE = '/basket'
export const SHOP_ROUTE = '/catalogue'
export const BOOK_ROUTE = '/book'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
